/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test
   public void testDiff_1() {
      ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4, 5));
      ArrayList<Integer> array2 = new ArrayList<>(Arrays.asList(1, 3, 8));
      assertTrue(App.ensureMeanOfLists(array,array2, 1));
    }

    @Test
    public void testNotDiff_7() {
      ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4, 5));
      ArrayList<Integer> array2 = new ArrayList<>(Arrays.asList(0, 2, 3, 4 , 7));
      assertFalse(App.ensureMeanOfLists(array,array2, 7));
    }

    @Test
    public void testEmptyArrays() {
      ArrayList<Integer> array = new ArrayList<>();
      ArrayList<Integer> array2 = new ArrayList<>();
      assertFalse(App.ensureMeanOfLists(array,array2, 1));
    }

    @Test
    public void testNull() {
      assertFalse(App.ensureMeanOfLists(null,null, 0));
    }

}
